language: php
dist: trusty
sudo: false
php: 7.1

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

branches:
  only:
    - /[0-9]+\.x/

mysql:
  database: polaris_cms
  username: root
  encoding: utf8

before_install:
  - source ./scripts/travis/init_env.sh

script:
# Installing polaris_site is the actual test
  - bash -x -e ./scripts/travis/install.sh
