# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: dennisdigital/drupalci:8-apache-interactive
    steps:
      - checkout
      - run:
          name: Composer
          command: |
            cd /var/www
            composer config --global --auth http-basic.repo.packagist.com dennisdigital ${PACKAGIST_TOKEN}
            composer create-project dennisdigital/polaris-drupal-project:dev-CMS-96_scaffolding polaris-cms --stability dev --no-interaction
      - save_cache:
          key: composer
          paths:
            - ~/.composer/cache
      - run:
          name: Prepare folders
          command: |
            cd /var/www
            mkdir -p polaris-cms/private
            mkdir -p polaris-cms/web/sites/default/files/behat-verbose
            mkdir -p polaris-cms/web/sites/simpletest
            chown -R www-data:www-data polaris-cms
      - run:
          name: Site install
          command: |
            cd /var/www/polaris-cms/web
            sudo -u www-data php core/scripts/drupal install polaris
            cd /var/www
            rm -rf html
            ln -s polaris-cms/web html
            echo "#drush si polaris --db-url=sqlite://sites/default/files/.ht.sqlite -y"
      - run:
          name: Run tests
          command: |
            cd /var/www/polaris-cms/web
            php core/scripts/run-tests.sh --keep-results --color --concurrency "31" --sqlite sites/default/files/.ht.sqlite --verbose polaris
      - store_artifacts:
          path: web/sites/default/files/behat-verbose
      - store_test_results:
          path: web/sites/default/files/behat-verbose

workflows:
  version: 2
  build:
    jobs:
      # - build
      - build:
          context: packagist
