# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: dennisdigital/drupalci:8-apache-interactive
    steps:
      - checkout

      - run:
          name: Build
          command: make build-profile

      # - run:
      #     name: Install Drupal
      #     command: make install-profile

      - run:
          name: Run tests
          command: make test-profile

      - store_artifacts:
          path: /var/www/polaris-cms/web/sites/default/files/simpletest
          destination: /tmp/results/simpletest

      - store_artifacts:
          path: /var/www/polaris-cms/web/sites/simpletest/browser_output
          destination: /tmp/results/simpletest/browser_output

      - store_artifacts:
          path: /var/www/polaris-cms/web/sites/default/files/behat-verbose
          destination: /tmp/results/behat-verbose

      - store_artifacts:
          path: /var/log/messages
          destination: /tmp/results/logs

      - store_test_results:
          path: /tmp/results

      - save_cache:
          key: composer
          paths:
            - ~/.composer/cache

workflows:
  version: 2
  build:
    jobs:
      # - build
      - build:
          context: packagist
