# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: dennisdigital/drupalci:8-apache-interactive
    steps:
      - checkout
      - run:
          name: Composer
          command: |
            cd /var/www
            composer config --global --auth http-basic.repo.packagist.com dennisdigital ${PACKAGIST_TOKEN}
            composer create-project dennisdigital/polaris-drupal-project:dev-CMS-96_scaffolding polaris_cms --stability dev --no-interaction
      - save_cache:
          key: composer
          paths:
            - ~/.composer/cache
      - run:
          name: Configure Apache
          command: |
            echo "<VirtualHost *:80>" > /etc/apache2/sites-enabled/000-default.conf
            echo "ServerAdmin webmaster@localhost" >> /etc/apache2/sites-enabled/000-default.conf
            echo "DocumentRoot /var/www/polaris_cms/web" >> /etc/apache2/sites-enabled/000-default.conf
            echo "ErrorLog ${APACHE_LOG_DIR}/error.log" >> /etc/apache2/sites-enabled/000-default.conf
            echo "CustomLog ${APACHE_LOG_DIR}/access.log combined" >> /etc/apache2/sites-enabled/000-default.conf
            echo "</VirtualHost>" >> /etc/apache2/sites-enabled/000-default.conf
            /etc/init.d/apache2 graceful
      - run:
          name: Prepare folders
          command: |
            cd /var/www
            mkdir -p polaris-cms/private
            mkdir -p polaris-cms/web/sites/default/files/behat-verbose
            mkdir -p polaris-cms/web/sites/simpletest
            chown -R www-data:www-data polaris-cms
      - run:
          name: Site install
          command: |
            cd /var/www/polaris-cms
            drush si polaris --db-url=sqlite://sites/default/files/.ht.sqlite -y
      - run:
          name: Run tests
          command: |
            cd /var/www/polaris-cms
            php core/scripts/run-tests.sh --keep-results --color --concurrency "31" --sqlite sites/default/files/.ht.sqlite --verbose polaris
      - store_artifacts:
          path: web/sites/default/files/behat-verbose
      - store_test_results:
          path: web/sites/default/files/behat-verbose

workflows:
  version: 2
  build:
    jobs:
      # - build
      - build:
          context: packagist
