# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-apache-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install PHP Extensions
          command: |
            sudo apt-get install -y libpng-dev
            sudo docker-php-ext-install gd
      - run:
          name: Install Drush
          command: |
            sudo curl -L -o /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.4.2/drush.phar
            sudo chmod +x /usr/local/bin/drush
      - run:
          name: Install Drupal console
          command: |
            sudo curl -L -o /usr/local/bin/drupal https://drupalconsole.com/installer
            sudo chmod +x /usr/local/bin/drupal
      - run:
          name: Composer
          command: |
            composer config --global --auth http-basic.repo.packagist.com dennisdigital ${PACKAGIST_TOKEN}
            composer create-project dennisdigital/polaris-drupal-project:dev-CMS-96_scaffolding polaris-cms --stability dev --no-interaction
      - save_cache:
          key: composer
          paths:
            - ~/.composer/cache
      - run:
          name: Site install
          command: |
            cd polaris-cms
            mkdir -p private && chmod -R 644 private
            cd web
            mkdir -p sites/default/files/behat-verbose
            drush si standard --db-url=sqlite://sites/default/files/.ht.sqlite -y
      - run:
          name: Run tests
          command: |
            cd cd polaris-cms/web
            php core/scripts/run-tests.sh --php /usr/local/bin/php --keep-results --color --concurrency "31" --sqlite sites/default/files/.ht.sqlite --verbose
      - store_artifacts:
          path: web/sites/default/files/behat-verbose
      - store_test_results:
          path: web/sites/default/files/behat-verbose

workflows:
  version: 2
  build:
    jobs:
      # - build
      - build:
          context: packagist
