# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-apache-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install PHP Extensions
          command: |
            sudo apt-get install -y libpng-dev
            sudo docker-php-ext-install gd
      - run:
          name: Install Drush
          command: |
            curl -L -o /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.4.2/drush.phar
            chmod +x /usr/bin/drush
      - run:
          name: Install Drupal console
          command: |
            curl -L -o /usr/local/bin/drupal https://drupalconsole.com/installer
            chmod +x /usr/bin/drupal
      - run:
          name: "Initialize"
          command: |
            cp .env.example .env
            mkdir -p private && chmod -R 644 private
      - run:
          name: Composer
          command: |
            composer config --global --auth http-basic.repo.packagist.com dennisdigital ${PACKAGIST_TOKEN}
            composer --verbose self-update --stable
            composer --verbose install
      - save_cache:
          key: composer
          paths:
            - ~/.composer/cache
      - run:
          name: Site install
          command: |
            cd web
            php core/scripts/drupal install polaris
      - run:
          name: Run tests
          command: |
            cd web
            php core/scripts/run-tests.sh --php /usr/local/bin/php --keep-results --color --concurrency "31" --sqlite sites/default/files/.ht.sqlite --verbose
      - store_artifacts:
          path: web/sites/default/files/behat-verbose
      - store_test_results:
          path: web/sites/default/files/behat-verbose

workflows:
  version: 2
  build:
    jobs:
      # - build
      - build:
          context: packagist
